import { db } from "./db";
import { users, projects, permits, tasks, notes } from "@shared/schema";
import { eq } from "drizzle-orm";

export async function seedDatabase() {
  const existingUsers = await db.select().from(users);
  if (existingUsers.length > 0) return;

  console.log("Seeding database...");

  const seedUsers = await db.insert(users).values([
    { name: "Al Quattrone", role: "Application Owner", email: "al@quattrone.com", isActive: true },
    { name: "Frank Feeney", role: "Project Manager", email: "frank@quattrone.com", isActive: true },
    { name: "Josh Eisenoff", role: "Associate Engineer", email: "josh@quattrone.com", isActive: true },
    { name: "Shelly Stalnos", role: "Office Manager", email: "shelly@quattrone.com", isActive: true },
    { name: "Jhonny Foronda", role: "Project Manager", email: "jhonny@quattrone.com", isActive: true },
    { name: "Jacob Soud", role: "Engineer", email: "jacob@quattrone.com", isActive: true },
    { name: "Jeff Falzone", role: "Planner", email: "jeff@quattrone.com", isActive: true },
    { name: "Sharon Hrabak", role: "Designer", email: "sharon@quattrone.com", isActive: true },
    { name: "Erick Diaz", role: "Engineer", email: "erick@quattrone.com", isActive: true },
    { name: "John Udart", role: "Engineer", email: "john@quattrone.com", isActive: true },
    { name: "Carson Tucker", role: "Engineer", email: "carson@quattrone.com", isActive: true },
    { name: "Angelica Hoffert", role: "Project Manager", email: "angelica@quattrone.com", isActive: true },
    { name: "David Castillo", role: "Project Manager", email: "david@quattrone.com", isActive: true },
  ]).returning();

  const [al, frank, josh, shelly, jhonny, jacob, jeff, sharon, erick, john, carson, angelica, david] = seedUsers;

  const seedProjects = await db.insert(projects).values([
    {
      name: "Coconut Point Mixed-Use Development",
      number: "QA-2024-001",
      description: "A 45-acre mixed-use development featuring retail, office, and residential components in Estero, FL. The project includes extensive stormwater management and environmental mitigation.",
      status: "Active",
      projectManagerId: frank.id,
      address: "23150 Fashion Dr, Estero, FL 33928",
      agency: "Lee County",
      strapNumber: "35-46-25-E4-0100A.0010",
      clientName: "Coconut Point Partners LLC",
      clientEmail: "dev@coconutpoint.com",
      clientMobile: "(239) 555-0101",
      clientOffice: "(239) 555-0100",
      architect: "HKS Architects",
      surveyor: "Banks Engineering",
      titlePolicyStatus: "Received",
      ballInCourt: "Quattrone & Associates",
      latitude: 26.4376,
      longitude: -81.8073,
    },
    {
      name: "Bonita Bay Residential Phase III",
      number: "QA-2024-002",
      description: "Third phase of luxury residential development at Bonita Bay, including 120 single-family lots with private amenities, clubhouse expansion, and golf course drainage improvements.",
      status: "Active Priority",
      projectManagerId: jhonny.id,
      address: "26660 Country Club Dr, Bonita Springs, FL 34134",
      agency: "City of Bonita Springs",
      strapNumber: "07-48-25-B2-00100.0550",
      clientName: "Bonita Bay Group Inc.",
      clientEmail: "info@bonitabay.com",
      clientMobile: "(239) 555-0201",
      architect: "Stofft Cooney Architects",
      biologist: "Passarella & Associates",
      landscaper: "Wilson Miller Inc.",
      surveyor: "Johnson Engineering",
      titlePolicyStatus: "Received",
      ballInCourt: "Lead Agency (City/County)",
      latitude: 26.3475,
      longitude: -81.7932,
    },
    {
      name: "Cape Coral Parkway Widening",
      number: "QA-2024-003",
      description: "FDOT-funded roadway widening project from 2 lanes to 4 lanes divided with bike lanes, sidewalks, and median landscaping along Cape Coral Parkway from Del Prado Blvd to Santa Barbara Blvd.",
      status: "Construction",
      projectManagerId: david.id,
      address: "1015 Cape Coral Pkwy E, Cape Coral, FL 33904",
      agency: "FDOT",
      strapNumber: "02-45-24-C1-00200.0010",
      clientName: "City of Cape Coral",
      clientEmail: "engineering@capecoral.gov",
      clientOffice: "(239) 555-0300",
      trafficEngineer: "Kittelson & Associates",
      surveyor: "Hole Montes Inc.",
      titlePolicyStatus: "Not Required",
      ballInCourt: "Quattrone & Associates",
      latitude: 26.5629,
      longitude: -81.9495,
    },
    {
      name: "Gateway Logistics Center",
      number: "QA-2024-004",
      description: "150,000 SF industrial warehouse and logistics facility near RSW Airport. Includes truck loading docks, employee parking, and retention pond system.",
      status: "Proposal",
      projectManagerId: angelica.id,
      address: "13500 Daniels Pkwy, Fort Myers, FL 33913",
      agency: "Lee County",
      strapNumber: "28-46-26-E1-00010.0200",
      clientName: "Gateway Development Corp",
      clientEmail: "proposals@gatewaycorp.com",
      clientMobile: "(239) 555-0401",
      architect: "Burt Hill Architects",
      titlePolicyStatus: "Pending",
      latitude: 26.5173,
      longitude: -81.7543,
    },
    {
      name: "Sanibel Causeway Bridge Rehabilitation",
      number: "QA-2023-088",
      description: "Post-hurricane structural assessment and rehabilitation of the Sanibel Causeway bridges, including seawall repairs, pile cap reinforcement, and coastal erosion mitigation.",
      status: "On Hold",
      projectManagerId: frank.id,
      address: "Sanibel Causeway, Sanibel, FL 33957",
      agency: "Lee County",
      strapNumber: "19-46-22-00-00001.0000",
      clientName: "Lee County DOT",
      clientEmail: "dot@leegov.com",
      clientOffice: "(239) 555-0500",
      biologist: "Turrell, Hall & Associates",
      titlePolicyStatus: "Not Required",
      ballInCourt: "Client / Owner",
      latitude: 26.4728,
      longitude: -82.0655,
    },
  ]).returning();

  const [proj1, proj2, proj3, proj4, proj5] = seedProjects;

  await db.insert(permits).values([
    {
      projectId: proj1.id,
      type: "Site Development Permit",
      number: "SDP-2024-0142",
      description: "Master site development permit for mixed-use complex",
      targetDate: "2024-06-15",
      submittalDate: "2024-05-20",
      applicationStatus: "Under Agency Review",
      feeStatus: "Paid",
      feeAmount: "$12,500",
      agency: "Lee County",
    },
    {
      projectId: proj1.id,
      type: "SFWMD Drainage Permitting",
      number: "ERP-2024-0089",
      description: "Environmental resource permit for stormwater system",
      targetDate: "2024-07-01",
      submittalDate: "2024-06-10",
      comments1Date: "2024-07-15",
      applicationStatus: "Comments Received",
      agency: "SFWMD",
    },
    {
      projectId: proj1.id,
      type: "Utility Permitting",
      number: "UP-2024-0234",
      description: "Water and sewer connection permit",
      targetDate: "2024-08-01",
      applicationStatus: "Fees Posted - Unpaid",
      feeStatus: "Unpaid",
      feeAmount: "$8,750",
      agency: "Lee County Utilities",
    },
    {
      projectId: proj2.id,
      type: "Building Permit",
      number: "BP-2024-1187",
      description: "Phase III residential building permits",
      targetDate: "2024-05-01",
      submittalDate: "2024-04-15",
      comments1Date: "2024-05-20",
      resubmittal1Date: "2024-06-01",
      approvalDate: "2024-06-20",
      expirationDate: "2026-06-20",
      applicationStatus: "Approved",
      feeStatus: "Paid",
      agency: "City of Bonita Springs",
    },
    {
      projectId: proj2.id,
      type: "SFWMD Drainage Permitting",
      number: "ERP-2024-0156",
      description: "Modify existing ERP for Phase III drainage",
      targetDate: "2024-09-15",
      submittalDate: "2024-08-01",
      applicationStatus: "Under Agency Review",
      agency: "SFWMD",
    },
    {
      projectId: proj2.id,
      type: "Veg Permit",
      number: "VP-2024-0045",
      description: "Vegetation removal and mitigation plan",
      targetDate: "2024-04-01",
      submittalDate: "2024-03-10",
      approvalDate: "2024-04-05",
      expirationDate: "2025-04-05",
      applicationStatus: "Approved",
      agency: "City of Bonita Springs",
    },
    {
      projectId: proj3.id,
      type: "FDOT Permit",
      number: "FDOT-2023-9876",
      description: "State highway access and construction permit",
      targetDate: "2023-12-01",
      submittalDate: "2023-11-15",
      approvalDate: "2024-01-10",
      expirationDate: "2025-07-10",
      applicationStatus: "Approved",
      feeStatus: "Paid",
      agency: "FDOT",
    },
    {
      projectId: proj3.id,
      type: "ROW Permit",
      number: "ROW-2024-0078",
      description: "Right-of-way utilization permit for median work",
      targetDate: "2024-03-15",
      submittalDate: "2024-02-28",
      approvalDate: "2024-03-20",
      expirationDate: "2025-03-20",
      applicationStatus: "Approved",
      agency: "Cape Coral",
    },
    {
      projectId: proj4.id,
      type: "Zoning Verification Letter",
      number: "",
      description: "Verify industrial zoning compliance for warehouse use",
      targetDate: "2025-04-15",
      applicationStatus: "Not Started",
      agency: "Lee County",
    },
  ]);

  const today = new Date();
  const daysFromNow = (d: number) => {
    const date = new Date(today);
    date.setDate(date.getDate() + d);
    return date.toISOString().split('T')[0];
  };
  const daysAgo = (d: number) => daysFromNow(-d);

  await db.insert(tasks).values([
    {
      projectId: proj1.id,
      name: "Prepare SFWMD resubmittal package",
      description: "Address all RAI comments from SFWMD on the ERP application. Update drainage calculations and revise plans per agency comments.",
      assignedBy: frank.name,
      assignedTo: josh.name,
      dueDate: daysFromNow(5),
      status: "In Progress",
      isImportant: true,
      tags: ["permits", "drainage"],
    },
    {
      projectId: proj1.id,
      name: "Update utility connection plans",
      description: "Revise water and sewer connection details per Lee County Utilities comments.",
      assignedBy: frank.name,
      assignedTo: erick.name,
      dueDate: daysFromNow(10),
      status: "Pending",
      isImportant: false,
      tags: ["utilities"],
    },
    {
      projectId: proj2.id,
      name: "Complete Phase III lot grading plans",
      description: "Finalize grading plans for lots 45-120 including drainage swales and building pad elevations.",
      assignedBy: jhonny.name,
      assignedTo: jacob.name,
      dueDate: daysFromNow(3),
      status: "In Progress",
      isImportant: true,
      tags: ["grading", "design"],
    },
    {
      projectId: proj2.id,
      name: "Coordinate with biologist on wetland buffer",
      description: "Schedule field meeting with Passarella & Associates to finalize wetland buffer delineation for lots near preserve area.",
      assignedBy: jhonny.name,
      assignedTo: carson.name,
      dueDate: daysFromNow(7),
      status: "Pending",
      isImportant: false,
      tags: ["environmental"],
    },
    {
      projectId: proj3.id,
      name: "Review contractor RFI responses",
      description: "Review and respond to 12 outstanding RFIs from the general contractor regarding utility conflicts and pavement sections.",
      assignedBy: david.name,
      assignedTo: john.name,
      dueDate: daysFromNow(2),
      status: "In Progress",
      isImportant: true,
      tags: ["construction", "RFI"],
    },
    {
      projectId: proj3.id,
      name: "Prepare monthly construction progress report",
      description: "Document construction progress, change orders, and schedule updates for FDOT monthly report submission.",
      assignedBy: david.name,
      assignedTo: sharon.name,
      dueDate: daysFromNow(14),
      status: "Pending",
      isImportant: false,
      tags: ["reporting"],
    },
    {
      projectId: proj1.id,
      name: "Client meeting prep - site plan review",
      description: "Prepare updated site plan exhibits for client presentation meeting scheduled next week.",
      assignedBy: frank.name,
      assignedTo: sharon.name,
      dateAssigned: daysAgo(10),
      dueDate: daysAgo(3),
      dateCompleted: daysAgo(2),
      status: "Completed",
      isImportant: false,
      tags: ["client"],
    },
    {
      projectId: proj4.id,
      name: "Draft preliminary site concept",
      description: "Create initial site layout concept for Gateway Logistics Center showing building footprint, truck courts, parking, and retention areas.",
      assignedBy: angelica.name,
      assignedTo: jeff.name,
      dueDate: daysFromNow(21),
      status: "Pending",
      isImportant: false,
      tags: ["design", "proposal"],
    },
  ]);

  await db.insert(notes).values([
    {
      projectId: proj1.id,
      type: "Client Meeting",
      body: "Met with Coconut Point Partners to review updated site plan. Client approved the revised building layout with the relocated retention pond. Next step is to update SFWMD application with new pond configuration.",
      date: daysAgo(5),
      author: frank.name,
    },
    {
      projectId: proj1.id,
      type: "Agency Correspondence",
      body: "Received RAI letter from SFWMD dated 7/15. Primary concerns: (1) Insufficient pre/post runoff calculations for 25-yr storm, (2) Need revised water quality calculations showing compliance with SFWMD criteria, (3) Wetland mitigation bank credit documentation needed.",
      date: daysAgo(3),
      author: josh.name,
    },
    {
      projectId: proj2.id,
      type: "Field Visit",
      body: "Conducted site inspection of Phase III area. Observed existing drainage patterns and identified potential conflicts with proposed lot grading near the western preserve boundary. Recommended 25-foot additional buffer from wetland edge.",
      date: daysAgo(7),
      author: jacob.name,
    },
    {
      projectId: proj3.id,
      type: "Internal Review",
      body: "Construction at 65% completion. Median work on schedule. Utility relocations delayed by 2 weeks due to FPL coordination issues. Bike lane striping to begin next month pending FDOT approval of updated MOT plans.",
      date: daysAgo(2),
      author: david.name,
    },
    {
      projectId: proj5.id,
      type: "General Comment",
      body: "Project remains on hold pending FEMA flood map revision review. Lee County DOT has requested we stand by for additional structural analysis once the new FIRM panels are published (expected Q2 2025).",
      date: daysAgo(14),
      author: frank.name,
    },
  ]);

  console.log("Database seeded successfully!");
}
